#========================================
# IT profile settings
#========================================
config:
  integration:
    token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
    datawarehousereader:
      url: http://localhost:${wiremock.server.port}/api-datawarehousereader
      client-id: the-client-id
      client-secret: the-client-secret
      connectTimeout: 5
      readTimeout: 30
